using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmashNet.Model
{
    public enum Games
    {
        Melee = 1,
        Pm = 2,
        SmashWiiU = 3,
        Smash64 = 4,
        Brawl = 5,
        Other = 6,
        StreetFighterV = 7,
        PokkenTournament = 8,
        LeagueOfLegends = 10,
        Dota2 = 11,
        Csgo = 12,
        Hearthstone = 13,
        RocketLeague = 14,
        Brawlhalla = 15,
        UltraStreetFighterIV = 16,
        Tekken7 = 17,
        UltimateMarvelvsCapcom3 = 18,
        KillerInstinct = 19,
        Splatoon = 20,
        GuiltyGearXrd = 21,
        MortalKombatX = 22,
        MortalKombatXl = 23,
        RivalsOfAether = 24,
        ClashRoyal = 25,
        Battlerite = 26,
        RockPaperScissors = 28,
        Smash3DS = 29,
        StarcraftII = 30,
        Overwatch = 31,
        Skullgirls2ndEncore = 32,
        Windjammers = 33,
        DiscJam = 34,
        Injustice2 = 35,
        GuiltyGearXrdRev2 = 36,
        BlazBlueCentralFiction = 37,
        TheKingOfFightersXIV = 38,
        CapcomVsSnk2 = 39,
        ForHonor = 40,
        Madden2017 = 41,
        PuyoPuyoVs2 = 42,
        BroodWar = 43,
        GearsOfWar4 = 45,
        Brawlout = 88,
        PokemonShowdown = 120,
        PokemonSunAndMoon = 143,
        Arms = 193,
        DragonBallFighterZ = 287,
        MarvelVsCapcomInfinite = 288,
        Deformers = 294,
        Splatoon2 = 327,
        PokemonTcgOnline = 342,
        PokemonTcg = 343,
        SoulcaliburV = 444,
        PokkenTournamentDx = 447,
        UnerNightInBirthExeLateSt = 451,
        Gwent = 556,
        Madden2018 = 562,
        FightingFloor = 573,
        VampireSavior = 582,
        FightOfGods = 608,
        StreetFighterIII = 610,
        StreetFighterII = 611,
        StreetFighterIV = 614
    }
}
